DROP USER IF EXISTS MAPPING;

DROP SERVER IF EXISTS server_pessoas CASCADE;

DROP EXTENSION IF EXISTS postgres_fdw;

DROP DATABASE IF EXISTS curriculum;
DROP DATABASE IF EXISTS access;
DROP DATABASE IF EXISTS pessoas;