"""empty message

Revision ID: fddfed5f1a29
Revises: 
Create Date: 2019-07-02 16:30:29.229213

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fddfed5f1a29'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('b03_aluno')
    op.drop_table('b13_rel_tr_cur')
    op.drop_table('b04_administrador')
    op.drop_table('b23_of_times')
    op.drop_table('b15_rel_pf_se')
    op.drop_table('b10_perfil')
    op.drop_table('b16_rel_prof_dis')
    op.drop_table('b01_pessoa')
    op.drop_table('b07_trilha')
    op.drop_table('b02_professor')
    op.drop_table('users')
    op.drop_table('b24_rel_dis_dis')
    op.drop_table('b18_rel_dis_mod')
    op.drop_table('b20_rel_pes_us')
    op.drop_table('b06_curso')
    op.drop_table('b21_oferecimento')
    op.drop_table('b19_rel_mod_cur')
    op.drop_table('b14_rel_us_pf')
    op.drop_table('b11_servico')
    op.drop_table('b05_disciplina')
    op.drop_table('b08_modulo')
    op.drop_table('b22_rel_al_of')
    op.drop_table('b17_rel_al_dis')
    op.drop_table('b12_rel_tr_mod')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('b12_rel_tr_mod',
    sa.Column('rel_tr_name', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('rel_mod_code', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('rel_tr_mod_mandatory', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['rel_mod_code'], ['b08_modulo.mod_code'], name='fk_mod_code', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rel_tr_name'], ['b07_trilha.tr_name'], name='fk_tr_name', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('rel_tr_name', 'rel_mod_code', name='pk_rel_tr_mod')
    )
    op.create_table('b17_rel_al_dis',
    sa.Column('rel_al_nusp', sa.VARCHAR(length=9), autoincrement=False, nullable=False),
    sa.Column('rel_dis_code', sa.VARCHAR(length=7), autoincrement=False, nullable=False),
    sa.Column('plan_semester', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('plan_year', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['rel_al_nusp'], ['b03_aluno.al_nusp'], name='fk_al_nusp', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rel_dis_code'], ['b05_disciplina.dis_code'], name='fk_dis_code', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('rel_al_nusp', 'rel_dis_code', name='pk_rel_al_dis')
    )
    op.create_table('b22_rel_al_of',
    sa.Column('rel_prof_nusp', sa.VARCHAR(length=9), autoincrement=False, nullable=False),
    sa.Column('rel_dis_code', sa.VARCHAR(length=7), autoincrement=False, nullable=False),
    sa.Column('rel_al_nusp', sa.VARCHAR(length=9), autoincrement=False, nullable=False),
    sa.Column('rel_al_of_year', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('rel_al_of_semester', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('rel_al_of_grade', sa.REAL(), autoincrement=False, nullable=True),
    sa.Column('rel_al_of_attendance', sa.REAL(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['rel_al_nusp'], ['b03_aluno.al_nusp'], name='fk_al_nusp', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rel_dis_code'], ['b05_disciplina.dis_code'], name='fk_dis_code', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rel_prof_nusp'], ['b02_professor.prof_nusp'], name='fk_prof_nusp', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('rel_prof_nusp', 'rel_dis_code', 'rel_al_nusp', 'rel_al_of_year', 'rel_al_of_semester', name='pk_rel_al_of')
    )
    op.create_table('b08_modulo',
    sa.Column('mod_id', sa.INTEGER(), server_default=sa.text("nextval('b08_modulo_mod_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('mod_code', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('mod_name', sa.VARCHAR(length=40), autoincrement=False, nullable=True),
    sa.Column('mod_cred_min', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.CheckConstraint('mod_cred_min > 0', name='cred_check'),
    sa.PrimaryKeyConstraint('mod_id', name='pk_modulo'),
    sa.UniqueConstraint('mod_code', name='sk_modulo'),
    postgresql_ignore_search_path=False
    )
    op.create_table('b05_disciplina',
    sa.Column('dis_id', sa.INTEGER(), server_default=sa.text("nextval('b05_disciplina_dis_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('dis_code', sa.VARCHAR(length=7), autoincrement=False, nullable=False),
    sa.Column('dis_name', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('dis_class_creds', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('dis_work_creds', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('dis_id', name='pk_disciplina'),
    sa.UniqueConstraint('dis_code', name='sk_disciplina'),
    postgresql_ignore_search_path=False
    )
    op.create_table('b11_servico',
    sa.Column('serv_id', sa.INTEGER(), server_default=sa.text("nextval('b11_servico_serv_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('serv_code', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('serv_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('serv_desc', sa.VARCHAR(length=280), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('serv_id', name='pk_servico'),
    sa.UniqueConstraint('serv_code', name='sk_servico'),
    postgresql_ignore_search_path=False
    )
    op.create_table('b14_rel_us_pf',
    sa.Column('rel_us_email', sa.NullType(), autoincrement=False, nullable=False),
    sa.Column('rel_perf_name', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('rel_us_pf_date_in', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('rel_us_pf_date_out', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['rel_perf_name'], ['b10_perfil.perf_name'], name='fk_perf_name', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rel_us_email'], ['users.us_email'], name='fk_us_email', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('rel_us_email', 'rel_perf_name', name='pk_rel_us_pf')
    )
    op.create_table('b19_rel_mod_cur',
    sa.Column('rel_mod_code', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('rel_cur_code', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['rel_cur_code'], ['b06_curso.cur_code'], name='fk_cur_code', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rel_mod_code'], ['b08_modulo.mod_code'], name='fk_mod_code', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('rel_mod_code', 'rel_cur_code', name='pk_rel_mod_cur')
    )
    op.create_table('b21_oferecimento',
    sa.Column('rel_prof_nusp', sa.VARCHAR(length=9), autoincrement=False, nullable=False),
    sa.Column('rel_dis_code', sa.VARCHAR(length=7), autoincrement=False, nullable=False),
    sa.Column('rel_oferecimento_year', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('rel_oferecimento_semester', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('rel_oferecimento_class', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['rel_dis_code'], ['b05_disciplina.dis_code'], name='fk_dis_code', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rel_prof_nusp'], ['b02_professor.prof_nusp'], name='fk_prof_nusp', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('rel_prof_nusp', 'rel_dis_code', 'rel_oferecimento_year', 'rel_oferecimento_semester', name='pk_oferecimento')
    )
    op.create_table('b06_curso',
    sa.Column('cur_id', sa.INTEGER(), server_default=sa.text("nextval('b06_curso_cur_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('cur_code', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('cur_name', sa.VARCHAR(length=60), autoincrement=False, nullable=True),
    sa.Column('adm_cpf', sa.VARCHAR(length=11), autoincrement=False, nullable=False),
    sa.Column('ad_cur_date_in', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('ad_cur_date_out', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['adm_cpf'], ['b04_administrador.adm_cpf'], name='fk_adm', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('cur_id', name='pk_curso'),
    sa.UniqueConstraint('cur_code', name='sk_curso'),
    postgresql_ignore_search_path=False
    )
    op.create_table('b20_rel_pes_us',
    sa.Column('rel_pes_cpf', sa.VARCHAR(length=11), autoincrement=False, nullable=False),
    sa.Column('rel_us_email', sa.NullType(), autoincrement=False, nullable=False),
    sa.Column('rel_pes_us_date_in', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('rel_pes_us_date_out', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['rel_pes_cpf'], ['b01_pessoa.pes_cpf'], name='fk_pes_cpf', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rel_us_email'], ['users.us_email'], name='fk_us_email', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('rel_pes_cpf', 'rel_us_email', name='pk_rel_pes_us')
    )
    op.create_table('b18_rel_dis_mod',
    sa.Column('rel_dis_code', sa.VARCHAR(length=7), autoincrement=False, nullable=False),
    sa.Column('rel_mod_code', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['rel_dis_code'], ['b05_disciplina.dis_code'], name='fk_dis_code', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rel_mod_code'], ['b08_modulo.mod_code'], name='fk_mod_code', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('rel_dis_code', 'rel_mod_code', name='pk_rel_dis_mod')
    )
    op.create_table('b24_rel_dis_dis',
    sa.Column('dis_code', sa.VARCHAR(length=7), autoincrement=False, nullable=False),
    sa.Column('dis_req_code', sa.VARCHAR(length=7), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['dis_code'], ['b05_disciplina.dis_code'], name='fk_dis', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['dis_req_code'], ['b05_disciplina.dis_code'], name='fk_req_dis', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('dis_code', 'dis_req_code', name='pk_rel_dis_dis')
    )
    op.create_table('users',
    sa.Column('us_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('us_email', sa.NullType(), autoincrement=False, nullable=True),
    sa.Column('us_password', sa.TEXT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('us_id', name='pk_user'),
    sa.UniqueConstraint('us_email', name='sk_user')
    )
    op.create_table('b02_professor',
    sa.Column('prof_id', sa.INTEGER(), server_default=sa.text("nextval('b02_professor_prof_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('prof_nusp', sa.VARCHAR(length=9), autoincrement=False, nullable=False),
    sa.Column('prof_cpf', sa.VARCHAR(length=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['prof_cpf'], ['b01_pessoa.pes_cpf'], name='fk_pessoa', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('prof_id', name='pk_professor'),
    sa.UniqueConstraint('prof_nusp', name='sk_professor'),
    postgresql_ignore_search_path=False
    )
    op.create_table('b07_trilha',
    sa.Column('tr_id', sa.INTEGER(), server_default=sa.text("nextval('b07_trilha_tr_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('tr_name', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('tr_id', name='pk_trilha'),
    sa.UniqueConstraint('tr_name', name='sk_trilha'),
    postgresql_ignore_search_path=False
    )
    op.create_table('b01_pessoa',
    sa.Column('pes_id', sa.INTEGER(), server_default=sa.text("nextval('b01_pessoa_pes_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('pes_cpf', sa.VARCHAR(length=11), autoincrement=False, nullable=False),
    sa.Column('pes_name', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('pes_id', name='pk_pessoa'),
    sa.UniqueConstraint('pes_cpf', name='sk_pessoa'),
    postgresql_ignore_search_path=False
    )
    op.create_table('b16_rel_prof_dis',
    sa.Column('rel_prof_nusp', sa.VARCHAR(length=9), autoincrement=False, nullable=False),
    sa.Column('rel_dis_code', sa.VARCHAR(length=7), autoincrement=False, nullable=False),
    sa.Column('rel_prof_disc_semester', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('rel_prof_disc_year', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['rel_dis_code'], ['b05_disciplina.dis_code'], name='fk_dis_code', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rel_prof_nusp'], ['b02_professor.prof_nusp'], name='fk_prof_nusp', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('rel_prof_nusp', 'rel_dis_code', name='pk_rel_prof_dis')
    )
    op.create_table('b10_perfil',
    sa.Column('perf_id', sa.INTEGER(), server_default=sa.text("nextval('b10_perfil_perf_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('perf_name', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('perf_desc', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('perf_id', name='pk_perfil'),
    sa.UniqueConstraint('perf_name', name='sk_perfil'),
    postgresql_ignore_search_path=False
    )
    op.create_table('b15_rel_pf_se',
    sa.Column('rel_perf_name', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('rel_serv_code', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['rel_perf_name'], ['b10_perfil.perf_name'], name='fk_perf_name', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rel_serv_code'], ['b11_servico.serv_code'], name='fk_serv_code', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('rel_perf_name', 'rel_serv_code', name='pk_rel_pf_se')
    )
    op.create_table('b23_of_times',
    sa.Column('prof_nusp', sa.VARCHAR(length=9), autoincrement=False, nullable=False),
    sa.Column('dis_code', sa.VARCHAR(length=7), autoincrement=False, nullable=False),
    sa.Column('year', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('semester', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('time_in', postgresql.TIME(), autoincrement=False, nullable=False),
    sa.Column('time_out', postgresql.TIME(), autoincrement=False, nullable=False),
    sa.Column('day', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['dis_code'], ['b05_disciplina.dis_code'], name='fk_dis', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['prof_nusp'], ['b02_professor.prof_nusp'], name='fk_prof', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('prof_nusp', 'dis_code', 'year', 'semester', 'time_in', 'day', name='pk_of_times')
    )
    op.create_table('b04_administrador',
    sa.Column('adm_id', sa.INTEGER(), server_default=sa.text("nextval('b04_administrador_adm_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('adm_cpf', sa.VARCHAR(length=11), autoincrement=False, nullable=False),
    sa.Column('adm_email', sa.NullType(), autoincrement=False, nullable=True),
    sa.Column('adm_dat_in', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('adm_dat_out', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['adm_cpf'], ['b01_pessoa.pes_cpf'], name='fk_pessoa', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('adm_id', name='pk_administrador'),
    sa.UniqueConstraint('adm_cpf', name='adm_cpf'),
    sa.UniqueConstraint('adm_email', name='sk_administrador'),
    postgresql_ignore_search_path=False
    )
    op.create_table('b13_rel_tr_cur',
    sa.Column('rel_tr_name', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('rel_cur_code', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['rel_cur_code'], ['b06_curso.cur_code'], name='fk_cur_code', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rel_tr_name'], ['b07_trilha.tr_name'], name='fk_tr_name', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('rel_tr_name', 'rel_cur_code', name='pk_rel_tr_cur')
    )
    op.create_table('b03_aluno',
    sa.Column('al_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('al_nusp', sa.VARCHAR(length=9), autoincrement=False, nullable=False),
    sa.Column('al_cpf', sa.VARCHAR(length=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['al_cpf'], ['b01_pessoa.pes_cpf'], name='fk_pessoa', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('al_id', name='pk_aluno'),
    sa.UniqueConstraint('al_nusp', name='sk_aluno')
    )
    # ### end Alembic commands ###
